### PR TITLE
install_rally.sh: Fix installing setuptools

### PR DESCRIPTION
**Pull request by mestery**
Upstream rally seems to have changed how rally is installed. Without this
change, I cannot get setuptools to install, and thus rally installation
fails.

Signed-off-by: Kyle Mestery mestery@mestery.com

### CODE REVIEW

**Comment by huikang** [comment]
@mestery I tried installing it on an ubuntu trusty host

```
git clone https://github.com/l8huang/rally rally_on_scale_test
cd rally_ovn_scale_test && ./install_rally.sh
```

I do not see any error.
Do you mind posting the error message you saw? Thanks.

**Comment by mestery** [comment]
Here are the errors I see:

```
ubuntu@ovn-rally:~/tmp$ git clone https://github.com/l8huang/rally rally_ovn_scale_test
Cloning into 'rally_ovn_scale_test'...
remote: Counting objects: 35902, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 35902 (delta 1), reused 0 (delta 0), pack-reused 35893
Receiving objects: 100% (35902/35902), 14.23 MiB | 8.85 MiB/s, done.
Resolving deltas: 100% (26619/26619), done.
Checking connectivity... done.
ubuntu@ovn-rally:~/tmp$ cd rally_ovn_scale_test && ./install_rally.sh
Installing Rally virtualenv in directory '/home/ubuntu/rally' ...
2016-06-09 01:56:29 URL:https://raw.githubusercontent.com/pypa/virtualenv/1.9.1/virtualenv.py [115013/115013] -> "/home/ubuntu/rally/virtualenv-191.py" [1]
Already using interpreter /usr/bin/python
New python executable in /home/ubuntu/rally/bin/python
Installing setuptools..............................done.
Installing pip...............................done.
2016-06-09 01:56:33 URL:https://pypi.python.org/simple/setuptools/ [125796/125796] -> "-" [1]
==========================================================
install_rally.sh: ERROR: Package 'setuptools' not found on PyPI!
==========================================================

Unable to download package 'setuptools' from PyPI.

If the above does not help you resolve the issue, please contact the
Rally team by sending an email to the OpenStack mailing list
openstack-dev@lists.openstack.org. Include the full output of this
script to help us identifying the problem.

Aborting installation!
tar (child): setuptools-*.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
==========================================================
install_rally.sh: ERROR: Failed to install the latest version of Python 'setuptools'
==========================================================


The required Python package setuptools could not be installed.


If the above does not help you resolve the issue, please contact the
Rally team by sending an email to the OpenStack mailing list
openstack-dev@lists.openstack.org. Include the full output of this
script to help us identifying the problem.

Aborting installation!
ubuntu@ovn-rally:~/tmp/rally_ovn_scale_test$ 
```

**Comment by huikang** [comment]
@mestery thanks for the detailed log message.
This might be an OS related issue, because I am installing the rally_ovs using a [Dockerfile](https://github.com/huikang/ovn-scale-test/blob/master/ansible/docker/rally/Dockerfile) and did not see the error. The dockerfile is based on ubuntu trusty.
Which OS version are you using?

**Comment by mestery** [comment]
@huikang: The version info is below:

ubuntu@ovn-rally:~/tmp/rally_ovn_scale_test$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty
ubuntu@ovn-rally:~/tmp/rally_ovn_scale_test$

**Pull request merged**
